components/getErg/Wallets.tsx

Change Satergo type icon to desktop

---

components/getErg/Mining.tsx

Hello, Ergo team!
We have discussed adding the link to the Kryptex pools previous week.
Here is a PR adding it.

Add kryptex mining pool link

---

components/shared/Post.tsx

[ISSUE-36][BUG] Fix tags css on blog post card

---

components/Footer.tsx

[ISSUE-49] Add latest blog posts and latest news to the footer

---

styles/globals.scss

[BUG][ISSUE-31] Fix faq colours

---

package-lock.json
package.json

Release -> 0.8.0

---

components/getErg/Mining.tsx

We've changed our pool domain and it would be great to change it on Ergo site as well.

Update Kryptex Pool link in Mining.tsx

---

components/getErg/Wallets.tsx
next.config.js
pages/ergo-wallet-app.tsx

https://github.com/ergoplatform/ergoweb/issues/74

Update ergo wallet app page

---

pages/blog/[id].tsx

Update h4 to h1 tag in blog post

---

pages/blog/[id].tsx
styles/globals.scss
styles/markdown-body.scss

[ISSUE-84] fix blog post styles

---

components/Footer.tsx
next-sitemap.config.js
next.config.js

[ISSUE-88] remove pt/es locales

---

styles/home.scss

[ISSUE-104] Fix background on blog post at landing page

---

components/getErg/Mining.tsx

Hello. Please add information about our mining pool on your website. If you need any addition information, please contact me - [stan@okminer.com](mailto:stan@okminer.com)
P.S. I hope I did everything right :)

Okminer info for ErgoWeb

---

pages/blog/[id].tsx

[ISSUE-113] fix blog post tags on mobile

---

components/getErg/GetErgHero.tsx

[ISSUE-115] make link cards responsive

---

pages/blog/[id].tsx

#134
I also changed the `Links` to regular anchor tags as it is an external link

[ISSUE-134] pass correct url to social share links

---

components/getErg/GetErgHero.tsx
components/home/UsingErg.tsx

#138 
also fixes weird height issues in Firefox

[ISSUE-138] add custom props to get-erg svgs

---

package-lock.json
package.json

Release -> 0.26.0

---

next.config.js

Activated Turkish language

---

content/compiled-locales/tr.json

All changes doing by me have been tested and ready to use without any errors. This file can be counted as working output.

Add Compiled Turkish Language

---

.storybook/preview.js

Add TR locale

---

pages/_app.tsx

Import Turkish language add and change nail " to '

Import Turkish Language

---

components/community/CommunityCardsFeed.tsx
components/getErg/Mining.tsx
components/shared/ContributeForm.tsx

update discord links

---

components/getErg/Wallets.tsx

I guess the link was meant to be the one I added

Updated link in wallet list
